### ISSUE TITLE
Doesn't work, or am I doing something wrong?

### ISSUE THREAD

**Issue by HimbeersaftLP** [99leonchang/PocketMine-Banners#4]
Getting this: <br />
<b>Fatal error</b>:  Call-time pass-by-reference has been removed in <b>/home/u534277387/public_html/pm-banners/banner/query.php</b> on line <b>60</b><br />

**Comment by xpyctum** [comment]
Upload your code. We need check.

**Comment by HimbeersaftLP** [comment]
Code? I uploaded the things here directly to my webserver...

**Comment by 99leonchang** [comment]
This is due to the fact that passing by reference at call-time is deprecated in 5.3 and removed in 5.4. Quick temporary fix would be to roll back to a previous PHP version, which I don't recommend. I'll take a look into it now.

**Comment by 99leonchang** [comment]
Should be fixed in latest commit.
Check it out and contact me if there are any more problems.

**Comment by HimbeersaftLP** [comment]
It shows that the server is offline, but it's online.
Example:
![](http://files.himbeer.me/pmbanners/banner1.php?host=play.lbsg.net&port=19132&name=LifeBoat)
